openapi: 3.2.0
info:
  title: Platform - Object Manager Object Task Management API
  version: '1.0'
  contact:
    name: OneTrust Support
    url: https://my.onetrust.com/s/contactsupport
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  description: The Object Manager APIs are used to integrate external systems and streamline the flow of data for objects created via Object Manager in the OneTrust Platform.
servers:
- url: https://{hostname}/api/custom-entity
  variables:
    hostname:
      default: hostname
      description: The OneTrust hostname such as app.onetrust.com, app-eu.onetrust.com, app-de.onetrust.com, app-uk.onetrust.com, app-apac.onetrust.com, trial.onetrust.com, or uat.onetrust.com.
tags:
- name: Object Task Management
  description: The Object Task Management APIs are used to manage tasks associated with objects.
  externalDocs:
    description: OpenAPI 3.1.0 - Download Definition
    url: https://developer.onetrust.com/onetrust/openapi/platform-object-manager.json
paths:
  /v1/tasks:
    post:
      operationId: createTaskUsingPOST_1
      summary: Create Task
      description: 'Use this API to create a new task for an object.


        > 🗒 Things to Know

        >

        > - This API only supports objects created via Object Manager, including Projects, Models, and Datasets.'
      tags:
      - Object Task Management
      x-onetrust:
        spec-label: https://developer.onetrust.com/onetrust/openapi/platform-object-manager.json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
            examples:
              Basic Task Creation:
                summary: Create a simple task with minimal details
                description: Creates a basic task with required fields only
                value:
                  name: Review compliance documentation
                  description: Review all compliance documentation for the latest model
                  entityId: a1b2c3d4-e5f6-7890-abcd-ef1234567890
                  status: Not Started
                  assignee: john.doe@example.com
                  dueDate: '2025-06-15T00:00:00Z'
              Comprehensive Task Creation:
                summary: Create a detailed task with all available fields
                description: Creates a comprehensive task with all optional fields specified
                value:
                  parentEntityId: c37283de-c93e-4da6-a3da-0c1791da5e33
                  taskName: task_04
                  description: <p>desc</p>
                  assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                  deadline: '2025-06-30T00:00:00.000'
                  orgGroupId: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                  taskTypeNameKey: ef4e5bf9-7462-43af-b74f-72b61308629b
                  priority: MEDIUM
                  collaborators:
                  - collaboratorId: 0d9739ff-541c-48d9-9861-c9b94ea6c1ae
                    type: GROUP
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInformation'
              examples:
                Task Creation Response:
                  summary: Sample response for a successful task creation
                  description: Task Creation Response
                  value:
                    id: 989f1de5-d41f-45d7-a93a-78f554a41f54
                    parentEntityId: c37283de-c93e-4da6-a3da-0c1791da5e33
                    taskName: task_04
                    taskType:
                      name: projects
                      nameKey: TaskRegistry.TaskType.ModuleTask.Name.Projects
                      module: CustomObject
                      moduleNameTranslationKey: TaskRegistry.Module.Name.CustomObject
                      id: 504ccd60-8966-40e6-bb6c-13f7d10dbfe7
                      label: null
                      icon: /cdn/static/images/onetrust/taskregistry/Projects.svg
                    deadline: '2025-06-30T00:00:00Z'
                    status: Open
                    priority: MEDIUM
                    description: <p>desc</p>
                    orgGroupId: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                    orgGroupAttribute:
                      valueKey: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                      value: PLTF REP
                    assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                    isActive: true
                    sourceType: null
                    sourceId: null
                    moduleSource: null
                    taskAssignmentInformations:
                    - userInfo:
                        name: Arpita K
                        nameWithAttributes: Arpita K
                      assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                      type: USER
                      isCollaborator: false
                    - userInfo:
                        name: Test User Group
                        nameWithAttributes: null
                      assigneeId: 0d9739ff-541c-48d9-9861-c9b94ea6c1ae
                      type: GROUP
                      isCollaborator: true
                    presentationMode: DRAWER
                    isCollaboratorSupported: true
                    isCollaboratorGroupSupported: true
                    relativeUrl: null
                    activity: COMPLETE_TASK
                    workflowAndStageBasicInformation: null
                    workflowId: null
                    workflowStageId: null
                    stageName: null
                    stageNameKey: null
                    badgeColor: null
                    dueDateInfo: null
                    permissionsMetadata: null
                    createdBy: 41955b71-e581-4187-ab6c-d00d1403350c
                    createdByAttribute:
                      valueKey: 41955b71-e581-4187-ab6c-d00d1403350c
                      value: Arpita K
                    createdDT: '2025-06-12T11:54:17.177Z'
                    modifiedBy: null
                    modifiedByAttribute: null
                    modifiedDT: null
                    completionDate: null
                    isRequired: false
                    canEditRequiredTask: null
                    pastDue: false
                    activityKey: TaskRegistry.ActivityKey.CompleteTask
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: "Too Many Requests. \nFor more information, see [API Rate Limits](https://developer.onetrust.com/onetrust/reference/rate-limits-overview)."
          headers:
            Retry-After:
              schema:
                description: The number of seconds after which requests will be allowed again.
                format: int32
            ot-period:
              schema:
                description: The unit of time for which the rate limit applies
                enum:
                - HOUR
                - MINUTE
            ot-ratelimit-event-id:
              schema:
                description: The unique identifier for the rate-limiting event.
                format: uuid
            ot-request-made:
              schema:
                description: The number of requests made within the specified period.
                format: int32
            ot-requests-allowed:
              schema:
                description: The number of requests allowed within the specified period.
                format: int32
        '500':
          description: Internal Server Error
      security:
      - OAUTH2:
        - OBJECT_MANAGER
        - OBJECT_MANAGER_READ
        - OBJECT_MANAGER_WRITE
        - INTEGRATION
  /v1/tasks/{taskId}:
    get:
      operationId: findTaskUsingGET_1
      summary: Get Task
      description: 'Use this API to retrieve a specific task on an object. The response will include details such as the activity history, assignee, and deadline.


        > 🗒 Things to Know

        >

        > - This API only supports objects created via Object Manager, including Projects, Models, and Datasets.'
      tags:
      - Object Task Management
      x-onetrust:
        spec-label: https://developer.onetrust.com/onetrust/openapi/platform-object-manager.json
      parameters:
      - name: taskId
        in: path
        description: The unique identifier of the task.
        required: true
        schema:
          description: Unique identifier of the task to retrieve
          type: string
          format: uuid
          example: 41955b71-e581-4187-ab6c-d00d1403350c
        example: 41955b71-e581-4187-ab6c-d00d1403350c
      - name: includePermissionsMetadata
        in: query
        description: This flag indicates whether to include permissions metadata.
        required: false
        schema:
          description: Whether to include permissions metadata in the response
          type: boolean
          default: false
        example: false
      - name: excludeInactiveTask
        in: query
        description: This flag indicates whether to exclude inactive tasks.
        required: false
        schema:
          description: Whether to exclude inactive tasks from the response
          type: boolean
          default: false
        example: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInformation'
              examples:
                Task Details Response:
                  summary: Sample response with complete task details
                  description: Task Details Response
                  value:
                    id: a1f229b1-8041-48ba-9354-ce90c03ce5b8
                    parentEntityId: 804c2939-c265-4181-9f52-fbdba80ff042
                    taskName: task_01
                    taskType:
                      name: datasets
                      nameKey: TaskRegistry.TaskType.ModuleTask.Name.Datasets
                      module: CustomObject
                      moduleNameTranslationKey: TaskRegistry.Module.Name.CustomObject
                      id: c569969c-94a9-4e2c-869d-e8334063d2ed
                      label: null
                      icon: null
                    deadline: '2025-07-01T00:00:00Z'
                    status: Open
                    priority: LOW
                    description: <p>desc</p>
                    orgGroupId: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                    orgGroupAttribute:
                      valueKey: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                      value: PLTF REP
                    assigneeId: 5689bde5-ed2e-47b4-9671-2185cdcd4d31
                    isActive: true
                    sourceType: null
                    sourceId: null
                    moduleSource: null
                    taskAssignmentInformations:
                    - userInfo:
                        name: User 1
                        nameWithAttributes: User 1
                      assigneeId: 5689bde5-ed2e-47b4-9671-2185cdcd4d31
                      type: USER
                      isCollaborator: false
                    - userInfo:
                        name: Arpita K
                        nameWithAttributes: Arpita K
                      assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                      type: USER
                      isCollaborator: true
                    - userInfo:
                        name: ADAN-7056_TEST
                        nameWithAttributes: null
                      assigneeId: 4265747b-ca7f-4b71-bfc0-93271214a41a
                      type: GROUP
                      isCollaborator: true
                    presentationMode: DRAWER
                    isCollaboratorSupported: true
                    isCollaboratorGroupSupported: true
                    relativeUrl: https://lkgb.1trust.app/ai-governance/datasets-type/datasets/804c2939-c265-4181-9f52-fbdba80ff042/details?context=eyJ0ZW5hbnRIYXNoIjoiJDJhJDEwJENSanpTWUJNSE1zeWk3dXE4RG1PZS5pZ3dQUm9XcFllSUFIdE1Wa0JoaGVGVVM2dmFNM0J5In0%3D&contextVersion=1
                    activity: COMPLETE_TASK
                    workflowAndStageBasicInformation: null
                    workflowId: null
                    workflowStageId: null
                    stageName: null
                    stageNameKey: null
                    badgeColor: null
                    dueDateInfo: null
                    permissionsMetadata: null
                    createdBy: 41955b71-e581-4187-ab6c-d00d1403350c
                    createdByAttribute:
                      valueKey: 41955b71-e581-4187-ab6c-d00d1403350c
                      value: Arpita K
                    createdDT: '2025-06-12T11:59:08.581Z'
                    modifiedBy: 41955b71-e581-4187-ab6c-d00d1403350c
                    modifiedByAttribute:
                      valueKey: 41955b71-e581-4187-ab6c-d00d1403350c
                      value: Arpita K
                    modifiedDT: '2025-06-12T12:04:06.048Z'
                    completionDate: null
                    isRequired: false
                    canEditRequiredTask: null
                    pastDue: false
                    activityKey: TaskRegistry.ActivityKey.CompleteTask
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: "Too Many Requests. \nFor more information, see [API Rate Limits](https://developer.onetrust.com/onetrust/reference/rate-limits-overview)."
          headers:
            Retry-After:
              schema:
                description: The number of seconds after which requests will be allowed again.
                format: int32
            ot-period:
              schema:
                description: The unit of time for which the rate limit applies
                enum:
                - HOUR
                - MINUTE
            ot-ratelimit-event-id:
              schema:
                description: The unique identifier for the rate-limiting event.
                format: uuid
            ot-request-made:
              schema:
                description: The number of requests made within the specified period.
                format: int32
            ot-requests-allowed:
              schema:
                description: The number of requests allowed within the specified period.
                format: int32
        '500':
          description: Internal Server Error
      security:
      - OAUTH2:
        - OBJECT_MANAGER
        - OBJECT_MANAGER_READ
        - OBJECT_MANAGER_WRITE
        - INTEGRATION
    put:
      operationId: updateTaskUsingPUT_1
      summary: Update Task
      description: 'Use this API to update an existing task for an object.


        > 🗒 Things to Know

        >

        > - This API only supports objects created via Object Manager, including Projects, Models, and Datasets.'
      tags:
      - Object Task Management
      x-onetrust:
        spec-label: https://developer.onetrust.com/onetrust/openapi/platform-object-manager.json
      parameters:
      - name: taskId
        in: path
        description: The unique identifier of the task.
        required: true
        schema:
          description: Unique identifier of the task to update
          type: string
          format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
            examples:
              Update Task Status:
                summary: Update task status and progress
                description: Updates a task's status and progress information
                value:
                  taskName: task_01
                  description: <p>desc</p>
                  assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                  deadline: '2025-06-30T00:00:00.000'
                  status: Open
                  priority: LOW
                  collaborators:
                  - collaboratorId: 41955b71-e581-4187-ab6c-d00d1403350c
                    type: USER
                  - collaboratorId: 4265747b-ca7f-4b71-bfc0-93271214a41a
                    type: GROUP
              Reassign Task:
                summary: Change task assignee and due date
                description: Reassigns a task to a different person and updates the due date
                value:
                  taskName: task_01
                  description: <p>desc</p>
                  assigneeId: 5689bde5-ed2e-47b4-9671-2185cdcd4d31
                  deadline: '2025-07-01T00:00:00.000'
                  status: Open
                  priority: LOW
                  collaborators:
                  - collaboratorId: 41955b71-e581-4187-ab6c-d00d1403350c
                    type: USER
                  - collaboratorId: 4265747b-ca7f-4b71-bfc0-93271214a41a
                    type: GROUP
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInformation'
              examples:
                Updated Task Response:
                  summary: Sample response for a successful task update
                  description: Updated Task Response
                  value:
                    id: a1f229b1-8041-48ba-9354-ce90c03ce5b8
                    parentEntityId: 804c2939-c265-4181-9f52-fbdba80ff042
                    taskName: task_01
                    taskType:
                      name: datasets
                      nameKey: TaskRegistry.TaskType.ModuleTask.Name.Datasets
                      module: CustomObject
                      moduleNameTranslationKey: TaskRegistry.Module.Name.CustomObject
                      id: c569969c-94a9-4e2c-869d-e8334063d2ed
                      label: null
                      icon: null
                    deadline: '2025-07-01T00:00:00Z'
                    status: Open
                    priority: LOW
                    description: <p>desc</p>
                    orgGroupId: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                    orgGroupAttribute:
                      valueKey: c9e5a35b-9be7-4dd6-adac-0bee7c02384f
                      value: PLTF REP
                    assigneeId: 5689bde5-ed2e-47b4-9671-2185cdcd4d31
                    isActive: true
                    sourceType: null
                    sourceId: null
                    moduleSource: null
                    taskAssignmentInformations:
                    - userInfo:
                        name: ADAN-7056_TEST
                        nameWithAttributes: null
                      assigneeId: 4265747b-ca7f-4b71-bfc0-93271214a41a
                      type: GROUP
                      isCollaborator: true
                    - userInfo:
                        name: User 1
                        nameWithAttributes: User 1
                      assigneeId: 5689bde5-ed2e-47b4-9671-2185cdcd4d31
                      type: USER
                      isCollaborator: false
                    - userInfo:
                        name: Arpita K
                        nameWithAttributes: Arpita K
                      assigneeId: 41955b71-e581-4187-ab6c-d00d1403350c
                      type: USER
                      isCollaborator: true
                    presentationMode: DRAWER
                    isCollaboratorSupported: true
                    isCollaboratorGroupSupported: true
                    relativeUrl: null
                    activity: COMPLETE_TASK
                    workflowAndStageBasicInformation: null
                    workflowId: null
                    workflowStageId: null
                    stageName: null
                    stageNameKey: null
                    badgeColor: null
                    dueDateInfo: null
                    permissionsMetadata: null
                    createdBy: 41955b71-e581-4187-ab6c-d00d1403350c
                    createdByAttribute:
                      valueKey: 41955b71-e581-4187-ab6c-d00d1403350c
                      value: Arpita K
                    createdDT: '2025-06-12T11:59:08.581Z'
                    modifiedBy: 41955b71-e581-4187-ab6c-d00d1403350c
                    modifiedByAttribute:
                      valueKey: 41955b71-e581-4187-ab6c-d00d1403350c
                      value: Arpita K
                    modifiedDT: '2025-06-12T12:04:05.812Z'
                    completionDate: null
                    isRequired: false
                    canEditRequiredTask: null
                    pastDue: false
                    activityKey: TaskRegistry.ActivityKey.CompleteTask
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: "Too Many Requests. \nFor more information, see [API Rate Limits](https://developer.onetrust.com/onetrust/reference/rate-limits-overview)."
          headers:
            Retry-After:
              schema:
                description: The number of seconds after which requests will be allowed again.
                format: int32
            ot-period:
              schema:
                description: The unit of time for which the rate limit applies
                enum:
                - HOUR
                - MINUTE
            ot-ratelimit-event-id:
              schema:
                description: The unique identifier for the rate-limiting event.
                format: uuid
            ot-request-made:
              schema:
                description: The number of requests made within the specified period.
                format: int32
            ot-requests-allowed:
              schema:
                description: The number of requests allowed within the specified period.
                format: int32
        '500':
          description: Internal Server Error
      security:
      - OAUTH2:
        - OBJECT_MANAGER
        - OBJECT_MANAGER_READ
        - OBJECT_MANAGER_WRITE
        - INTEGRATION
components:
  schemas:
    TaskTypeInformation:
      type: object
      properties:
        name:
          description: The name of the task type.
          type: string
          example: DOCUMENT_REVIEW
          maxLength: 100
          minLength: 1
        nameKey:
          description: The name key of the task type used for translation purposes.
          type: string
          example: TaskRegistry.TaskType.DocumentReview
          maxLength: 255
          minLength: 1
        module:
          description: The source product of the task type.
          type: string
          example: ASSESSMENT
          maxLength: 100
          minLength: 1
        moduleNameTranslationKey:
          description: The name key of the product used for translation purposes.
          type: string
          example: TaskRegistry.Module.Assessment
          maxLength: 255
          minLength: 1
        id:
          description: The unique identifier of the task type.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        label:
          description: The display label of the task type.
          type: string
          example: Document Review
          maxLength: 255
          minLength: 1
        icon:
          description: The icon of the task type.
          type: string
          example: document-check
          maxLength: 50
          minLength: 1
      example:
        id: 123e4567-e89b-12d3-a456-426614174000
        name: DOCUMENT_REVIEW
        nameKey: TaskRegistry.TaskType.DocumentReview
        module: ASSESSMENT
        moduleNameTranslationKey: TaskRegistry.Module.Assessment
        label: Document Review
        icon: document-check
      required:
      - id
      - label
      - module
      - moduleNameTranslationKey
      - name
      - nameKey
    UserInfo:
      type: object
      properties:
        name:
          description: The name of the user or user group.
          type: string
          example: John Doe
        nameWithAttributes:
          description: The name of the user or user group with additional attributes.
          type: string
          example: 'John Doe (Admin, Department: IT)'
      example:
        name: John Doe
        nameWithAttributes: 'John Doe (Admin, Department: IT)'
      required:
      - name
    TaskInformation:
      type: object
      properties:
        id:
          description: The unique identifier of the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        parentEntityId:
          description: The unique identifier of the parent record where the task was created.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        taskName:
          description: The name of the task.
          type: string
          example: Review Document XYZ
          maxLength: 255
          minLength: 1
        taskType:
          description: The details of the task type.
          example:
            id: 123e4567-e89b-12d3-a456-426614174000
            name: Document Review
            description: Review and approve documents
          $ref: '#/components/schemas/TaskTypeInformation'
        deadline:
          description: The date and time by which the task should be completed.
          type: string
          format: date-time
          example: '2023-12-31T23:59:59Z'
        status:
          description: The status of the task.
          type: string
          example: Open
          enum:
          - Open
          - Closed
        priority:
          description: The priority level of the task.
          type: string
          example: MEDIUM
          enum:
          - LOW
          - MEDIUM
          - HIGH
        description:
          description: The description of the task.
          type: string
          example: This task requires reviewing document X and providing feedback
          maxLength: 4000
        orgGroupId:
          description: The unique identifier of the organization responsible for the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
          deprecated: true
        orgGroupAttribute:
          description: The attribute details of the organization responsible for the task.
          example:
            value: OneTrust LLC
            valueKey: 123e4567-e89b-12d3-a456-426614174000
          $ref: '#/components/schemas/AttributeValue'
        assigneeId:
          description: The unique identifier of the user assigned as an assignee on the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        isActive:
          description: This flag indicates whether the task is active.
          type: boolean
          example: true
          default: 'true'
        sourceType:
          description: The type of source that created the task.
          type: string
          example: RULES
          maxLength: 50
        sourceId:
          description: The unique identifier of the source that created the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        moduleSource:
          description: The source product of the task.
          type: string
          example: assessment
          enum:
          - assessment
          - audit-mgmt
          - cyber-risk
          - data-mapping
          - data-governance
          - esg
          - erm
          - incident
          - issue
          - itrm
          - program-benchmarking
          - maturity-planning
          - risk
          - vendor
          - vendor-portal
          - compliance-automation
          - SpeakUp
          - EntityScoping
          - ControlObjective
          - exception
        taskAssignmentInformations:
          description: The details of the task assignment.
          type: array
          items:
            $ref: '#/components/schemas/TaskAssignmentInformation'
          example:
          - assigneeId: 123e4567-e89b-12d3-a456-426614174000
            assigneeName: John Doe
            assignmentType: PRIMARY
        presentationMode:
          description: The presentation mode of the task.
          type: string
          example: DEFAULT
          enum:
          - NAVIGATION
          - DRAWER
        isCollaboratorSupported:
          description: This flag indicates whether users can be assigned as collaborators on the task.
          type: boolean
          example: true
          default: 'false'
        isCollaboratorGroupSupported:
          description: This flag indicates whether user groups can be assigned as collaborators on the task.
          type: boolean
          example: true
          default: 'false'
        relativeUrl:
          description: The relative URL associated with the task.
          type: string
          example: /tasks/review/123
          maxLength: 255
        activity:
          description: The type of activity for the task.
          type: string
          example: COMPLETE_TASK
          enum:
          - COMPLETE_TASK
          - REVIEW_DSARSUBTASK
          - APPROVE_RISK
          - RESPOND_TO_ASSESSMENT
          - COMPLETE_AUDIT
          - REVIEW_REQUEST
          - COURSE_COMPLETION_PENDING
          - REVIEW_ASSESSMENT
          - REVIEW_INCIDENT
          - IMPLEMENT_CONTROL
          - RISK_TREATMENT
          - REVIEW_FINDING
          - ACKNOWLEDGE_TO_ATTESTATION
          - REVIEW_INITIATIVE
          - COMPLETE_DISCLOSURE
          - COMPLETE_DISCLOSURE_ATTESTATION
          - EVIDENCE_TASK
          - COMPLETE_DISC_QUESTIONNAIRE
          - COMPLIANCE_INITIATIVE
          - REVIEW_ISSUE
          - CASE_ASSIGNED
          - SPEAK_UP_QUESTION_ASSIGNED
          - CONTROL_OBJECTIVE
          - REVIEW_EXCEPTION
        workflowAndStageBasicInformation:
          description: The details of the workflow and stage.
          type: object
          example:
            workflowName: Document Approval Workflow
            currentStage: Review Stage
            stageOrder: 2
        workflowId:
          description: The unique identifier of the workflow.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        workflowStageId:
          description: The unique identifier of the workflow stage.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        stageName:
          description: The name of the workflow stage.
          type: string
          example: Review
          maxLength: 255
        stageNameKey:
          description: The name key of the workflow stage used for translation purposes.
          type: string
          example: TaskRegistry.Stage.Review
          maxLength: 255
        badgeColor:
          description: The badge color of the workflow stage.
          type: string
          example: '#4287f5'
          maxLength: 7
        dueDateInfo:
          description: The details of the task due date.
          $ref: '#/components/schemas/DueDateInfo'
        permissionsMetadata:
          description: The permissions metadata for the task.
          type: object
          additionalProperties:
            type: boolean
        createdBy:
          description: The unique identifier of the user who created the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
          deprecated: true
        createdByAttribute:
          description: The attribute details of the user who created the task.
          example:
            value: Jane Smith
            valueKey: 456e7890-e89b-12d3-a456-426614174000
          $ref: '#/components/schemas/AttributeValue'
        createdDT:
          description: The date and time that the task was created.
          type: string
          format: date-time
          example: '2023-01-15T14:30:00Z'
        modifiedBy:
          description: The unique identifier of the user who modified the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
          deprecated: true
        modifiedByAttribute:
          description: The attribute details of the user who modified the task.
          example:
            value: Jane Smith
            valueKey: 456e7890-e89b-12d3-a456-426614174000
          $ref: '#/components/schemas/AttributeValue'
        modifiedDT:
          description: The date and time that the task was modified.
          type: string
          format: date-time
          example: '2023-01-20T16:45:00Z'
        completionDate:
          description: The date and time that the task was completed.
          type: string
          format: date-time
          example: '2023-01-25T09:15:00Z'
        isRequired:
          description: This flag indicates whether the task is required.
          type: boolean
          example: true
          default: 'false'
        canEditRequiredTask:
          description: This flag indicates whether the task can be edited.
          type: boolean
          example: false
          default: 'false'
        pastDue:
          description: This flag indicates whether the task is past due.
          type: boolean
        activityKey:
          description: The key of the activity type used for translation purposes.
          type: string
          deprecated: true
      example:
        id: 123e4567-e89b-12d3-a456-426614174000
        taskName: Document Review Task
        status: Open
        priority: MEDIUM
        deadline: '2023-12-31T23:59:59Z'
        description: This task requires reviewing document X and providing feedback
        assigneeId: 123e4567-e89b-12d3-a456-426614174000
        isActive: true
        taskType:
          id: type-123
          name: Document Review
          description: Review and approve documents
        moduleSource: PRIVACY_RIGHTS
        activity: COMPLETE_TASK
        presentationMode: DEFAULT
        isCollaboratorSupported: true
        relativeUrl: /tasks/review/123
        workflowId: workflow-456
        stageName: Review
        isPastDue: false
        createdDT: '2023-01-15T14:30:00Z'
        modifiedDT: '2023-01-20T16:45:00Z'
        isRequired: true
      required:
      - deadline
      - id
      - isActive
      - parentEntityId
      - priority
      - status
      - taskName
      - taskType
    TaskContextInformation:
      type: object
      properties:
        parameters:
          description: This parameter can be used to store details in key value pairs.
          additionalProperties:
            type: object
          example:
            taskId: 123e4567-e89b-12d3-a456-426614174000
            priority: HIGH
            assignedTo: john.doe@example.com
          type: object
      example:
        parameters:
          assignedTo: john.doe@example.com
          priority: HIGH
          taskId: 123e4567-e89b-12d3-a456-426614174000
    TaskCollaboratorDto:
      type: object
      properties:
        collaboratorId:
          description: The unique identifier of the user assigned as a collaborator on the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        collaboratorEmail:
          description: The email address of the user assigned as a collaborator on the task.
          type: string
          example: collaborator@example.com
          maxLength: 255
          minLength: 5
        type:
          description: 'The type of collaborator. '
          type: string
          example: USER
          enum:
          - USER
          - GROUP
      example:
        collaboratorId: 123e4567-e89b-12d3-a456-426614174000
        collaboratorEmail: collaborator@example.com
        type: USER
      required:
      - type
    TaskCreateRequest:
      type: object
      properties:
        parentEntityId:
          description: The unique identifier of the parent record where the task was created.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        taskName:
          description: The name of the task.
          type: string
          example: Review document
          maxLength: 512
          minLength: 1
        description:
          description: The description of the task.
          type: string
          example: Please review the attached document and provide feedback
          maxLength: 2000
        orgGroupId:
          description: The unique identifier of the organization responsible for the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        taskTypeNameKey:
          description: The name key of the task type used for translation purposes.
          type: string
          example: REVIEW_TASK
          maxLength: 100
          minLength: 1
        assigneeId:
          description: The unique identifier of the user assigned as an assignee on the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        assigneeEmail:
          description: The email address of the user assigned as an assignee on the task.
          type: string
          example: user@example.com
          maxLength: 255
          minLength: 5
        collaborators:
          description: The details of the collaborators assigned to the task.
          type: array
          items:
            $ref: '#/components/schemas/TaskCollaboratorDto'
        deadline:
          description: The date and time by which the task should be completed.
          type: string
          format: date-time
          example: '2023-12-31T23:59:59'
        context:
          description: The contextual details of the task.
          $ref: '#/components/schemas/TaskContextInformation'
        isActive:
          description: This flag indicates whether the task is active.
          type: boolean
          example: true
          default: 'false'
        sourceType:
          description: The type of source that created the task.
          type: string
          example: RULES
          maxLength: 16
        sourceId:
          description: The unique identifier of the source that created the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        resourceId:
          description: The unique identifier of the parent record where the task was created.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        resourceTypeNameKey:
          description: The key used to identify the type of resource.
          type: string
          example: ASSESSMENT
          maxLength: 100
          minLength: 1
        moduleSource:
          description: The source product of the task.
          type: string
          enum:
          - assessment
          - audit-mgmt
          - cyber-risk
          - data-mapping
          - data-governance
          - esg
          - erm
          - incident
          - issue
          - itrm
          - program-benchmarking
          - maturity-planning
          - risk
          - vendor
          - vendor-portal
          - compliance-automation
          - SpeakUp
          - EntityScoping
          - ControlObjective
          - exception
        priority:
          description: The priority level of the task.
          type: string
          example: MEDIUM
          default: MEDIUM
          enum:
          - LOW
          - MEDIUM
          - HIGH
        isRequired:
          description: This flag indicates whether the task is required.
          type: boolean
          example: false
          default: 'false'
      example:
        parentEntityId: 123e4567-e89b-12d3-a456-426614174000
        taskName: Review document
        description: Please review the attached document and provide feedback
        orgGroupId: 123e4567-e89b-12d3-a456-426614174000
        taskTypeNameKey: REVIEW_TASK
        assigneeId: 123e4567-e89b-12d3-a456-426614174000
        deadline: '2023-12-31T23:59:59'
        priority: MEDIUM
      required:
      - orgGroupId
      - parentEntityId
      - taskName
      - taskTypeNameKey
    TaskUpdateRequest:
      type: object
      properties:
        taskName:
          description: The name of the task.
          type: string
          example: Review document
          maxLength: 512
          minLength: 1
        description:
          description: The description of the task.
          type: string
          example: Please review the attached document and provide feedback
          maxLength: 2000
        assigneeId:
          description: The unique identifier of the user assigned as an assignee on the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        assigneeEmail:
          description: The email address of the user assigned as an assignee on the task.
          type: string
          example: user@example.com
          maxLength: 255
          minLength: 5
        collaborators:
          description: The details of the collaborators assigned to the task.
          type: array
          items:
            $ref: '#/components/schemas/TaskCollaboratorDto'
        deadline:
          description: The date and time by which the task should be completed.
          type: string
          format: date-time
          example: '2023-12-31T23:59:59'
        status:
          description: The status of the task.
          type: string
          example: Open
          enum:
          - Open
          - Closed
        context:
          description: The contextual details of the task.
          $ref: '#/components/schemas/TaskContextInformation'
        priority:
          description: The priority level of the task.
          type: string
          example: MEDIUM
          default: MEDIUM
          enum:
          - LOW
          - MEDIUM
          - HIGH
        isRequired:
          description: This flag indicates whether the task is required.
          type: boolean
          example: false
          default: 'false'
        sourceType:
          description: The type of source that created the task.
          type: string
          example: RULES
          maxLength: 16
          minLength: 1
        sourceId:
          description: The unique identifier of the source that created the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
      example:
        taskName: Review document
        description: Please review the attached document and provide feedback
        assigneeId: 123e4567-e89b-12d3-a456-426614174000
        deadline: '2023-12-31T23:59:59'
        status: Open
        priority: MEDIUM
      required:
      - taskName
    AttributeValue:
      type: object
      properties:
        valueKey:
          description: The name key of the attribute used for translation purposes.
          type: string
          example: f47ac10b-58cc-4372-a567-0e02b2c3d479
          maxLength: 255
          minLength: 1
        value:
          description: The name of the attribute.
          type: string
          example: Document Review Team
          maxLength: 255
          minLength: 1
      example:
        valueKey: f47ac10b-58cc-4372-a567-0e02b2c3d479
        value: Document Review Team
      required:
      - value
      - valueKey
    DueDateInfo:
      type: object
      properties:
        date:
          description: The date and time that the task is due.
          type: string
          format: date-time
          example: '2023-12-31T23:59:59Z'
        color:
          description: The color code for displaying the task due date.
          type: string
          example: '#FF0000'
          maxLength: 7
          minLength: 1
        icon:
          description: The icon of the task due date.
          type: string
          example: clock-warning
          maxLength: 50
          minLength: 1
        textKey:
          description: The text key to display with the task due date used for translation purposes.
          type: string
          example: TaskRegistry.DueDate.Overdue
          maxLength: 255
          minLength: 1
        numberOfDays:
          description: The number of days until or past the task due date.
          type: integer
          format: int64
          example: 5
      example:
        date: '2023-12-31T23:59:59Z'
        color: '#FF0000'
        icon: clock-warning
        textKey: TaskRegistry.DueDate.Overdue
        numberOfDays: 5
      required:
      - color
      - date
      - icon
      - numberOfDays
      - textKey
    TaskAssignmentInformation:
      type: object
      properties:
        userInfo:
          description: The details of the users or user groups responsible for the task.
          $ref: '#/components/schemas/UserInfo'
        assigneeId:
          description: The unique identifier of the user or user group assigned to the task.
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type:
          description: 'The type of assignee or collaborator. '
          type: string
          example: USER
          enum:
          - USER
          - GROUP
        isCollaborator:
          description: This flag indicates whether the user or user group was added as a collaborator.
          type: boolean
          example: false
          default: 'false'
      example:
        taskId: 123e4567-e89b-12d3-a456-426614174000
        userInfo:
          id: 123e4567-e89b-12d3-a456-426614174001
          name: John Doe
        assigneeId: 123e4567-e89b-12d3-a456-426614174000
        type: USER
        isCollaborator: false
      required:
      - assigneeId
      - isCollaborator
      - type
  securitySchemes:
    OAUTH2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{hostname}/api/access/v1/oauth/token
          scopes:
            OBJECT_MANAGER: Grants full access to Object Manager related APIs.
            OBJECT_MANAGER_READ: Grants read access to Object Manager related APIs
            OBJECT_MANAGER_WRITE: Grants write access to Object Manager related APIs
x-onetrust:
  spec-label: OpenAPI 3.1.0
  links:
  - '{''Object Manager'': ''https://my.onetrust.com/s/topic/0TO3q000000JPkQGAW/object-manager''}'
x-readme:
  explorer-enabled: false
  proxy-enabled: false
  metrics-enabled: false
